1. Google data search [https://datasetsearch.research.google.com/]
2. World bank open data [https://data.worldbank.org/]
3. Data.gov [https://data.gov/]
4. European Data [https://data.europa.eu/en]
5. UC Irvine Machine Learning Repository [https://archive.ics.uci.edu/]
6. Nasdaq Data [https://data.nasdaq.com/institutional-investors]
7. Havard data verse [https://dataverse.harvard.edu/]
8. Pew research [https://www.pewresearch.org/instructions-for-downloading-datasets/]
9. African Information Highwway [https://www.afdb.org/en/knowledge/statistics/africa-information-highway-aih]
10. Open data AWS [https://registry.opendata.aws/]
